vim.g.mapleader = ' '
vim.g.maplocalleader = ' '

vim.o.hlsearch = false -- Highlight on search
vim.wo.number = true -- Relative line numbers
vim.wo.relativenumber = true
vim.o.mouse = '' -- No mouse mode
-- vim.o.clipboard = 'unnamedplus' -- Sync clipboard between OS and Neovim.
vim.o.breakindent = true -- Enable break indent
vim.o.undofile = true -- Save undo history
vim.o.ignorecase = true -- Case-insensitive searching UNLESS \C or capital in search
vim.o.smartcase = true
vim.wo.signcolumn = 'yes' -- Keep signcolumn on by default
vim.o.updatetime = 250 -- Decrease update time
vim.o.timeout = true
vim.o.timeoutlen = 300
vim.o.completeopt = 'menuone,noselect' -- Set completeopt to have a better completion experience
vim.o.termguicolors = true -- NOTE: You should make sure your terminal supports this
vim.o.scrolloff = 5
vim.o.cursorline = true
-- vim.o.guicursor = '' -- Old school cursor
vim.o.tabstop = 2
vim.o.softtabstop = 2
vim.o.shiftwidth = 2
vim.o.expandtab = true
vim.o.smarttab = true
vim.o.linebreak = true
